# Generated by Django 4.2.1 on 2023-07-20 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0005_alter_follow_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=33)),
                ('message_handler', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(null=True)),
                ('ip_addr', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=8)),
                ('room_name', models.CharField(max_length=255)),
                ('is_public', models.IntegerField(choices=[(0, 'only user that know room code can join'), (1, 'Anyone can join, room will shown in chat index')], default=1)),
                ('active_bots', models.ManyToManyField(blank=True, null=True, to='Chat.bot')),
                ('blocked_users', models.ManyToManyField(blank=True, null=True, related_name='blocked_users_set', to='User.user')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Chat.room')),
            ],
        ),
    ]
