# Generated by Django 4.2.1 on 2023-07-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Jockey', '0003_audio_jockey_token'),
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Audio_Jockey.audio_jockey'),
        ),
    ]
