# Generated by Django 4.2.1 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_coins'),
        ('Chat', '0002_alter_room_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active_bots',
            field=models.ManyToManyField(to='Chat.bot'),
        ),
        migrations.AlterField(
            model_name='room',
            name='blocked_users',
            field=models.ManyToManyField(related_name='blocked_users_set', to='User.user'),
        ),
    ]
