# Generated by Django 4.2.2 on 2023-12-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Jockey', '0005_audio_jockey_usertype_alter_audio_jockey_uid'),
        ('Chat', '0002_alter_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio_Jockey.audio_jockey'),
        ),
    ]
