# Generated by Django 4.2.2 on 2023-12-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_alter_userspent_time_created_date'),
        ('Chat', '0003_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificationupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.common')),
            ],
        ),
    ]
