# Generated by Django 4.2.1 on 2023-07-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_coins'),
        ('Chat', '0003_alter_room_active_bots_alter_room_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active_bots',
            field=models.ManyToManyField(blank=True, to='Chat.bot'),
        ),
        migrations.AlterField(
            model_name='room',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_users_set', to='User.user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(max_length=500),
        ),
    ]
