# Generated by Django 4.2.2 on 2023-12-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_notificationupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
