# Generated by Django 4.2.1 on 2023-07-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_room_active_bots_alter_room_blocked_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_Image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(max_length=8),
        ),
    ]
