# Generated by Django 4.2.1 on 2023-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0005_room_room_image_alter_room_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
