# Generated by Django 4.0.1 on 2023-06-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coins_club_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins_club_owner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
