# Generated by Django 4.2.2 on 2023-06-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coins_club_owner', '0002_coins_club_owner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins_club_owner',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
