# Generated by Django 4.2.2 on 2023-08-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Dob', models.DateField(blank=True, default='')),
                ('profile_picture', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Introduction_voice', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Introduction_text', models.CharField(default='', max_length=500)),
                ('Invitation_Code', models.IntegerField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('usertype', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('Otpcreated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coins', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Follow1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='master.common')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='master.common')),
            ],
        ),
    ]
