# Generated by Django 4.2.2 on 2023-08-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
