# Generated by Django 4.2.2 on 2023-08-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_common_email_alter_common_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='common',
            name='email',
        ),
        migrations.RemoveField(
            model_name='common',
            name='phone',
        ),
    ]
