# Generated by Django 4.2.2 on 2023-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_remove_common_email_remove_common_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='email',
            field=models.EmailField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='common',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
