# Generated by Django 4.2.2 on 2023-08-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_common_email_common_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='common',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
