# Generated by Django 4.2.2 on 2023-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_alter_common_email_alter_common_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='Is_Approved',
            field=models.BooleanField(default=False),
        ),
    ]
