# Generated by Django 4.2.2 on 2023-09-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_alter_social_media_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='Facebook',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='Snapchat',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
