# Generated by Django 4.2.2 on 2023-09-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_alter_social_media_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social_media',
        ),
    ]
