# Generated by Django 4.2.2 on 2023-12-12 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_follow_claim_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_claim_coins',
            name='created_at',
        ),
        migrations.AddField(
            model_name='follow_claim_coins',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
