# Generated by Django 4.2.2 on 2023-12-12 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0015_remove_follow_claim_coins_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_JockeyFollow_claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.common')),
            ],
        ),
    ]
