# Generated by Django 4.2.2 on 2023-12-12 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Jockey', '0001_initial'),
        ('master', '0017_remove_follow1_created_date_follow1_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_JockeyFollow_claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio_Jockey.audio_jockey')),
            ],
        ),
    ]
