# Generated by Django 4.2.2 on 2023-12-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0018_audio_jockeyfollow_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_jockeyfollow_claim',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.common'),
        ),
    ]
