# Generated by Django 4.2.2 on 2023-12-16 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0020_cointransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cointransaction',
            old_name='timestamp',
            new_name='created_date',
        ),
    ]
