# Generated by Django 4.2.2 on 2023-12-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_rename_timestamp_cointransaction_created_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinTransaction',
            new_name='CoinTransactionhistory',
        ),
    ]
