# Generated by Django 4.2.2 on 2023-12-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_rename_cointransaction_cointransactionhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinTransactionhistory',
            new_name='GiftTransactionhistory',
        ),
    ]
