# Generated by Django 4.2.2 on 2023-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0023_rename_cointransactionhistory_gifttransactionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifttransactionhistory',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
