# Generated by Django 4.2.2 on 2023-12-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0025_userspenttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpent_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time_duration', models.DurationField()),
            ],
        ),
    ]
