# Generated by Django 4.2.2 on 2023-12-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0026_userspent_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSpentTime',
        ),
    ]
