# Generated by Django 4.2.2 on 2023-12-19 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0027_delete_userspenttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspent_time',
            name='date',
        ),
        migrations.AddField(
            model_name='userspent_time',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
