# Generated by Django 4.2.2 on 2023-12-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0028_remove_userspent_time_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspent_time',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
