# Generated by Django 4.2.2 on 2023-12-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0029_alter_userspent_time_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspent_time',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
