# Generated by Django 4.2.2 on 2023-12-11 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jockey_club_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Jockey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Dob', models.DateField(blank=True, default='')),
                ('profile_picture', models.CharField(default='', max_length=200)),
                ('Introduction_voice', models.CharField(default='', max_length=200)),
                ('Introduction_text', models.CharField(default='', max_length=500)),
                ('Club_Owner_Phone_Number', models.CharField(max_length=15)),
                ('Club_Owner_Email_id', models.EmailField(max_length=254)),
                ('National_ID', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Pan_Card', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Bank_Acc_Details', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('UPI_Address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Paytm_Address', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('uid', models.CharField(blank=True, max_length=50, null=True)),
                ('usertype', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(blank=True, max_length=300, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('Otpcreated_at', models.DateTimeField(blank=True, null=True)),
                ('Is_Approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('Club_Owner_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jockey_club_owner.jockey_club_owner')),
            ],
        ),
    ]
