# Generated by Django 4.2.1 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coins_trader', '0003_coins_trader_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins_trader',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
