# Generated by Django 4.0.1 on 2023-06-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jockey_club_owner', '0002_jockey_club_owner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jockey_club_owner',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
