# Generated by Django 4.0.1 on 2023-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jockey_club_owner', '0003_jockey_club_owner_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jockey_club_owner',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
