# Generated by Django 4.2.1 on 2023-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jockey_club_owner', '0004_alter_jockey_club_owner_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='jockey_club_owner',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
