# Generated by Django 4.0.1 on 2023-06-29 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('Gender', models.CharField(default='', max_length=20)),
                ('Dob', models.DateField(blank=True, default='')),
                ('profile_picture', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Introduction_voice', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('Introduction_text', models.CharField(default='', max_length=500)),
                ('Invitation_Code', models.IntegerField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=8, null=True)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('Otpcreated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
