# Generated by Django 4.2.2 on 2023-12-11 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jockey_club_owner', '0001_initial'),
        ('User', '0003_jockey_club_ownerdaliyclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockeyclubownerlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jockey_club_owner.jockey_club_owner')),
            ],
        ),
    ]
