# Generated by Django 4.2.2 on 2023-12-11 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_jockeyclubownerlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiojockeyloigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Jockey_club_ownerdaliyclaim',
        ),
    ]
