# Generated by Django 4.2.2 on 2023-12-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Jockey', '0001_initial'),
        ('User', '0005_audiojockeyloigin_delete_jockey_club_ownerdaliyclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiojockeyloigin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio_Jockey.audio_jockey'),
        ),
    ]
