# Generated by Django 4.2.2 on 2023-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_user_usertype_alter_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_Approved',
            field=models.BooleanField(default=True),
        ),
    ]
