# Generated by Django 4.2.2 on 2023-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Google', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Facebook', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Snapchat', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
