# Generated by Django 4.2.2 on 2023-10-13 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='follow_claim_coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.DateTimeField(max_length=100)),
                ('created_at', models.DateTimeField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
