# Generated by Django 4.2.2 on 2023-10-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_follow_claim_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='claim_coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_at', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.DeleteModel(
            name='follow_claim_coins',
        ),
    ]
