# Generated by Django 4.2.2 on 2023-10-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_follow_claim_coins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow_claim_coins',
        ),
    ]
