# Generated by Django 4.2.2 on 2023-11-20 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room_join_claim_coins',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
