# Generated by Django 4.2.2 on 2023-11-20 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_rename_created_at_room_join_claim_coins_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_join_claim_coins',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
