# Generated by Django 4.2.2 on 2023-11-21 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_rename_created_date_claim_coins_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim_coins',
            name='created_at',
        ),
        migrations.AddField(
            model_name='claim_coins',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
