# Generated by Django 4.2.2 on 2023-12-12 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jockey_club_owner', '0006_jockey_club_owner_usertype_and_more'),
        ('Coins_trader', '0005_coins_trader_usertype_alter_coins_trader_uid'),
        ('Audio_Jockey', '0005_audio_jockey_usertype_alter_audio_jockey_uid'),
        ('Coins_club_owner', '0005_coins_club_owner_usertype_alter_coins_club_owner_uid'),
        ('User', '0022_delete_paymentgatway_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockeyclubownerlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jockey_club_owner.jockey_club_owner')),
            ],
        ),
        migrations.CreateModel(
            name='Coinsclubownerdaliylogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coins_club_owner.coins_club_owner')),
            ],
        ),
        migrations.CreateModel(
            name='Coins_traderdaliylogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coins_trader.coins_trader')),
            ],
        ),
        migrations.CreateModel(
            name='Audiojockeyloigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio_Jockey.audio_jockey')),
            ],
        ),
    ]
