# Generated by Django 4.2.2 on 2023-12-13 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Audio_Jockey', '0005_audio_jockey_usertype_alter_audio_jockey_uid'),
        ('User', '0024_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_create_claim_coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_coins', models.BooleanField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Audio_Jockey.audio_jockey')),
            ],
        ),
    ]
