# Generated by Django 4.2.2 on 2023-12-14 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_remove_top_fan_list_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Top_Fan_list',
        ),
    ]
