# Generated by Django 4.2.2 on 2024-01-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0030_alter_userspent_time_created_date'),
        ('coin', '0005_purches_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purches_history',
            new_name='Purchase_history',
        ),
    ]
