# Generated by Django 4.2.2 on 2024-01-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0006_rename_purches_history_purchase_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history',
            name='claim_coins',
            field=models.CharField(max_length=100),
        ),
    ]
